{
    "plugins": [
        ["@semantic-release/commit-analyzer", {
            "preset": "angular",
            "releaseRules": [
                {"type": "breaking", "release": "major"},
                {"type": "feature", "release": "minor"},
            ]
        }],
        ["@semantic-release/npm", {
            "npmPublish": false,
            "tarballDir": "dist",
        }],
        ["@mob-sakai/semantic-release-git-snapshot", {
            "snapshotPrefix": "./Assets/Mirror",
            "snapshotBranch": "snapshot",
            "snapshotTagFormat": "${version}"
        }]
    ]
}
