{
    tagFormat: "${version}-master",
    "plugins": [
        "@semantic-release/github",
        "@semantic-release/release-notes-generator", 
        ["@semantic-release/commit-analyzer", {
            "preset": "angular",
            "releaseRules": [
                {"type": "breaking", "release": "major"},
                {"type": "feature", "release": "minor"},
            ]
        }],
        ["@semantic-release/changelog", {
            "changelogFile": "Assets/Mirror/CHANGELOG.md",
        }],
        ["@semantic-release/npm", {
            "npmPublish": false,
            "pkgRoot": "Assets/Mirror"
        }],
        ["@semantic-release/git", {
            "assets": ["Assets/Mirror/package.json", "Assets/Mirror/CHANGELOG.md"],
            "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
        }],
        ["@semantic-release/exec", {
            "publishCmd": "./publish_upm.sh upm ${nextRelease.version}"
        }]
    ]
}
