{
    tagFormat: "${version}-master",
    "plugins": [
        "@semantic-release/github",
        "@semantic-release/release-notes-generator", 
        ["@semantic-release/commit-analyzer", {
            "preset": "angular",
            "releaseRules": [
                {"type": "breaking", "release": "major"},
                {"type": "feature", "release": "minor"},
            ]
        }],
        ["@semantic-release/npm", {
            "npmPublish": false,
            "pkgRoot": "Assets/Mirror"
        }],
        ["@semantic-release/exec", {
            "publishCmd": "git subtree push --prefix=Assets/Mirror origin upmtest && git tag upmtest ${nextRelease.version} && git push origin --tags"
        }]
    ]
}
