{

    "plugins": [
        "@semantic-release/github",
        "@semantic-release/release-notes-generator", 
        ["@semantic-release/commit-analyzer", {
            "preset": "angular",
            "releaseRules": [
                {"type": "breaking", "release": "major"},
                {"type": "feature", "release": "minor"},
            ]
        }],
        ["@semantic-release/npm", {
            "npmPublish": false,
            "pkgRoot": "Assets/Mirror"
        }],
        ["@mob-sakai/semantic-release-git-snapshot", {
            "snapshotPrefix": "./Assets/Mirror",
            "snapshotBranch": "upmtest",
            "snapshotTagFormat": "${version}"
        }]
    ]
}
