// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverGeneratedReaderWriterTests.GivesErrorForInvalidArraySegmentType")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverGeneratedReaderWriterTests.GivesErrorForInvalidArrayType")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverGeneratedReaderWriterTests.GivesErrorForInvalidListType")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverGeneratedReaderWriterTests.GivesErrorWhenUsingAbstractClass")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverGeneratedReaderWriterTests.GivesErrorWhenUsingInterface")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverGeneratedReaderWriterTests.GivesErrorWhenUsingMonoBehaviour")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverGeneratedReaderWriterTests.GivesErrorWhenUsingObject")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverGeneratedReaderWriterTests.GivesErrorWhenUsingScriptableObject")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverGeneratedReaderWriterTests.GivesErrorWhenUsingTypeInheritedFromMonoBehaviour")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverNetworkBehaviourTests.NetworkBehaviourClientRpcParamAbstract")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverNetworkBehaviourTests.NetworkBehaviourClientRpcParamComponent")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverNetworkBehaviourTests.NetworkBehaviourClientRpcParamRef")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverNetworkBehaviourTests.NetworkBehaviourCmdParamAbstract")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Tests.WeaverSyncVarTests.SyncVarsMoreThan63")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.ClientRpcProcessor.GenerateRegisterRemoteDelegate(Mono.Cecil.Cil.ILProcessor,Mono.Cecil.MethodDefinition,System.String)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.ClientRpcProcessor.GenerateStub(Mono.Cecil.MethodDefinition,Mono.Cecil.CustomAttribute)~Mono.Cecil.MethodDefinition")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.PropertySiteProcessor.ProcessInstructionLoadAddress(Mono.Cecil.MethodDefinition,Mono.Cecil.Cil.Instruction,Mono.Cecil.FieldDefinition)~Mono.Cecil.Cil.Instruction")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Readers.GenerateArraySegmentReadFunc(Mono.Cecil.TypeReference)~Mono.Cecil.MethodDefinition")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.RpcProcessor.ReadArguments(Mono.Cecil.MethodDefinition,Mono.Cecil.Cil.ILProcessor,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.RpcProcessor.SubstituteMethod(Mono.Cecil.MethodDefinition)~Mono.Cecil.MethodDefinition")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.RpcProcessor.WriteArguments(Mono.Cecil.Cil.ILProcessor,Mono.Cecil.MethodDefinition,Mono.Cecil.Cil.VariableDefinition,Mirage.Weaver.RemoteCallType)~System.Boolean")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.ServerRpcProcessor.GenerateStub(Mono.Cecil.MethodDefinition,Mono.Cecil.CustomAttribute)~Mono.Cecil.MethodDefinition")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.SyncObjectProcessor.GenerateSyncObjectRegistration(Mono.Cecil.Cil.ILProcessor,Mono.Cecil.FieldDefinition)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.SyncVarProcessor.DeserializeField(Mono.Cecil.FieldDefinition,Mono.Cecil.Cil.ILProcessor,Mono.Cecil.MethodDefinition)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.SyncVarProcessor.GenerateDeSerialization(Mono.Cecil.TypeDefinition)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.SyncVarProcessor.GenerateSerialization(Mono.Cecil.TypeDefinition)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.SyncVarProcessor.GenerateSyncVarSetter(Mono.Cecil.FieldDefinition,System.String,System.Int64,Mono.Cecil.TypeReference)~Mono.Cecil.MethodDefinition")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Writers.GenerateCollectionWriter(Mono.Cecil.TypeReference,Mono.Cecil.TypeReference,System.Linq.Expressions.Expression{System.Action})~Mono.Cecil.MethodDefinition")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Writers.WriteNullCheck(Mono.Cecil.Cil.ILProcessor)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Readers.GenerateNullCheck(Mono.Cecil.Cil.ILProcessor)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirage.Weaver.Readers.GenerateReadCollection(Mono.Cecil.TypeReference,Mono.Cecil.TypeReference,System.Linq.Expressions.Expression{System.Action})~Mono.Cecil.MethodDefinition")]
