// DO NOT EDIT: GENERATED BY ZigZagTestGenerator.cs

using System;
using System.Collections;
using Mirage.Serialization;
using Mirage.Tests.Runtime.ClientServer;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;

namespace Mirage.Tests.Runtime.Generated.ZigZagAttributeTests
{
    %%EXTRA_TYPE%%
    public class ZigZagBehaviour_%%TYPE%%_%%BIT_COUNT%%%%EXTRA_NAME%% : NetworkBehaviour
    {
        [BitCount(%%BIT_COUNT%%), ZigZagEncode]
        [SyncVar] public %%TYPE%% myValue;
    }
    public class ZigZagTest_%%TYPE%%_%%BIT_COUNT%%%%EXTRA_NAME%% : ClientServerSetup<ZigZagBehaviour_%%TYPE%%_%%BIT_COUNT%%%%EXTRA_NAME%%>
    {
        const %%TYPE%% value = %%EXTRA_VALUE%%;

        [Test]
        public void SyncVarIsBitPacked()
        {
            serverComponent.myValue = value;

            using (PooledNetworkWriter writer = NetworkWriterPool.GetWriter())
            {
                serverComponent.SerializeSyncVars(writer, true);

                Assert.That(writer.BitPosition, Is.EqualTo(%%BIT_COUNT%%));

                using (PooledNetworkReader reader = NetworkReaderPool.GetReader(writer.ToArraySegment()))
                {
                    clientComponent.DeserializeSyncVars(reader, true);
                    Assert.That(reader.BitPosition, Is.EqualTo(%%BIT_COUNT%%));

                    Assert.That(clientComponent.myValue, Is.EqualTo(value));
                }
            }
        }
    }
}
